from tkinter import *


window = Tk()

window.title("Calculadora")
window.resizable(False, False)
titulo = Label(window, text="Calculadora")
titulo.config(font=("Verdana", 19))
titulo.grid(column=0, row=0, columnspan=4, pady=7)
boton_0 = Button(window, text="0")
boton_1 = Button(window, text="1")
boton_2 = Button(window, text="2")
boton_3 = Button(window, text="3")
boton_4 = Button(window, text="4")
boton_5 = Button(window, text="5")
boton_6 = Button(window, text="6")
boton_7 = Button(window, text="7")
boton_8 = Button(window, text="8")
boton_9 = Button(window, text="9")
boton_suma = Button(window, text="+")
boton_resta = Button(window, text="-")
boton_multiplicacion = Button(window, text="*")
boton_division = Button(window, text="/")
boton_igual = Button(window, text="=")
boton_1.grid(column=0, row=1, pady=7, padx=3)
boton_2.grid(column=1, row=1, padx=3)
boton_3.grid(column=2, row=1)
boton_4.grid(column=0, row=2, pady=7, padx=3)
boton_5.grid(column=1, row=2, padx=3)
boton_6.grid(column=2, row=2)
boton_7.grid(column=0, row=3, pady=7, padx=3)
boton_8.grid(column=1, row=3, padx=3)
boton_9.grid(column=2, row=3)
boton_0.grid(column=1, row=4)
boton_suma.grid(column=4, row=1, pady=7)
boton_resta.grid(column=4, row=2, pady=7)
boton_multiplicacion.grid(column=4, row=3, pady=7)
boton_division.grid(column=4, row=4, pady=7)
boton_igual.grid(column=0, row=5, columnspan=4)
boton_igual.config(width=20)

window.mainloop()
